version: '3.8'

services:
  db:
    build: .
    container_name: adtech-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: AdTech            # початкова схема
      MYSQL_USER: adtech
      MYSQL_PASSWORD: adtechpass
    command: --local-infile=1           # дозволяє LOAD DATA LOCAL INFILE
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
#      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "-prootpass"]
      interval: 10s
      retries: 5

volumes:
  mysql_data:
